### ISSUE TITLE
CDN问题

### ISSUE THREAD

**Issue by Mr-metasequoia** [YunYouJun/hexo-tag-common#4]
云游君，使用CDN似乎有问题，tag-common将无法正确显示。

错误显示：
![image](https://user-images.githubusercontent.com/76619254/170923854-508ef163-725a-4c69-b894-60ebecc27c0a.png)

关闭CDN后可以正常显示。

正确显示：
![image](https://user-images.githubusercontent.com/76619254/170924054-dda5737f-ca66-46d7-895d-d314fd43e108.png)

**Comment by YunYouJun** [comment]
由于国内 jsdelivr 默认 CDN (`cdn.jsdelivr.net`)已被污染，请检查是否如下配置 CDN:

```yml
tag_common:
  cdn: https://fastly.jsdelivr.net/npm/
```

**Comment by Mr-metasequoia** [comment]
我按照默认的配置
![image](https://user-images.githubusercontent.com/76619254/171006594-861bafaf-9a19-400c-adce-ae559f01a960.png)

我发现：
1. 如果设置https://fastly.jsdelivr.net/npm/  ，pc端chrome正常显示，edge和移动端异常显示（当然我用了shift+f5）
2. 如果设置false，则pc端和移动端都正常显示

另外，我使用的是yun主题。
（感觉没有什么影响的话，我就设置cdn:false了……）

**Comment by YunYouJun** [comment]
先设置 false，使用本地资源吧，速度差异可以忽略不计。

最近 CDN 不稳定。

**Comment by YunYouJun** [comment]
我测试本身设置后链接是没问题的，应该只是网络或缓存问题。

**Comment by Mr-metasequoia** [comment]
应该是网络的问题，兴许是网太慢了有些东西没加载出来。
非常感谢你为这个issue花的时间！
