### ISSUE TITLE
关于插件中的图标

### ISSUE THREAD

**Issue by wgx-dh** [YunYouJun/hexo-tag-common#5]
hexo-theme-yun 主题更换了图标
希望本插件中也适配相同的图标配置方法
![image](https://user-images.githubusercontent.com/63238251/172041865-a5b12ef1-0bf8-4bb7-8b3a-880b551481c0.png)

**Comment by YunYouJun** [comment]
Added in `v0.2.0`.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/25154432/172246161-c1ef8370-a99b-40a2-839b-e1b597dfcb0b.png">
